export enum NotificationType {
  WELCOME = "WELCOME",
  VERIFY_EMAIL = "VERIFY_EMAIL",
  PASSWORD_RESET = "PASSWORD_RESET",
  ORDER_PLACED = "ORDER_PLACED",
  ORDER_CONFIRMED = "ORDER_CONFIRMED",
  ORDER_PREPARING = "ORDER_PREPARING",
  ORDER_READY = "ORDER_READY",
  ORDER_COMPLETED = "ORDER_COMPLETED",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  REFUND_SUCCESS = "REFUND_SUCCESS",
  SYSTEM_ALERT = "SYSTEM_ALERT",
  LOW_STOCK = "LOW_STOCK"
}

export enum NotificationChannel {
  EMAIL = "EMAIL",
  IN_APP = "IN_APP",
  SMS = "SMS",
  PUSH = "PUSH"
}
