export enum SocketEvent {
  ORDER_CREATED = "ORDER_CREATED",
  ORDER_STATUS_UPDATED = "ORDER_STATUS_UPDATED",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  LOW_STOCK = "LOW_STOCK",
  NEW_NOTIFICATION = "NEW_NOTIFICATION"
}
